/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fqFX8XEgvhZ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
"use client";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
   SelectValue,
   SelectTrigger,
   SelectItem,
   SelectContent,
   Select,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Button } from "@/components/ui/button";
import { Textarea } from "../ui/textarea";
import { useCreateUserModal } from "@/hooks/use-create-user-modal";
import { useCreateKategoriaShpenzimeveModal } from "@/hooks/use-create-kategoriaShepnzimeve-modal";
import { useCreateShpenzimetModal } from "@/hooks/use-create-shpenzimet-modal";

export function CreateUser() {
   const userModal = useCreateUserModal();
   const kategoriaShpenzimeveModal = useCreateKategoriaShpenzimeveModal();
   const shpenzimetModal = useCreateShpenzimetModal();
   return (
      <div className="flex gap-2">
         <Button onClick={() => userModal.onOpen()}>Shto user te ri</Button>
         <Button onClick={() => kategoriaShpenzimeveModal.onOpen()}>Shto kategori te shpenzimeve</Button>
         <Button onClick={() => shpenzimetModal.onOpen()}>Shto shpenzim te ri</Button>
      </div>
   );
}
