/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Xpe7jZkcDPD
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Button } from "@/components/ui/button";

export function Faturat() {
   return (
      <div className="max-w-xl mx-auto p-6 bg-white border rounded-lg w-full">
         <div className="flex items-center justify-between mb-4">
            <h1 className="text-xl font-bold">Faturat</h1>
            <div>
               <Button className="mr-2" variant="outline">
                  Add Invoice
               </Button>
               <Button variant="outline">View All</Button>
            </div>
         </div>
         <div className="space-y-4">
            <div className="flex justify-between items-center">
               <div>
                  <p className="text-gray-500">March, 01, 2024</p>
                  <p className="text-gray-700 font-bold">#MS-415646</p>
               </div>
               <div className="flex items-center">
                  <span className="text-gray-900 font-bold">$180</span>
               </div>
            </div>
            <div className="flex justify-between items-center">
               <div>
                  <p className="text-gray-500">March, 01, 2024</p>
                  <p className="text-gray-700 font-bold">#MS-415646</p>
               </div>
               <div className="flex items-center">
                  <span className="text-gray-900 font-bold">$180</span>
               </div>
            </div>
            <div className="flex justify-between items-center">
               <div>
                  <p className="text-gray-500">March, 01, 2024</p>
                  <p className="text-gray-700 font-bold">#MS-415646</p>
               </div>
               <div className="flex items-center">
                  <span className="text-gray-900 font-bold">$180</span>
               </div>
            </div>
            <div className="flex justify-between items-center">
               <div>
                  <p className="text-gray-500">March, 01, 2024</p>
                  <p className="text-gray-700 font-bold">#MS-415646</p>
               </div>
               <div className="flex items-center">
                  <span className="text-gray-900 font-bold">$180</span>
               </div>
            </div>
            <div className="flex justify-between items-center">
               <div>
                  <p className="text-gray-500">March, 01, 2024</p>
                  <p className="text-gray-700 font-bold">#MS-415646</p>
               </div>
               <div className="flex items-center">
                  <span className="text-gray-900 font-bold">$180</span>
               </div>
            </div>
         </div>
      </div>
   );
}
