/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/BuqarXwTwOZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"

export function PagesaInfo() {
  return (
    <div className="flex p-4 bg-white rounded-lg shadow space-x-4">
      <div className="flex-1 space-y-1">
        <h3 className="text-lg font-semibold">Oliver Liam</h3>
        <p className="text-sm text-gray-600">Bank Name: Raiffeisen</p>
        <p className="text-sm text-gray-600">Email Address: oliver@burrito.com</p>
        <p className="text-sm text-gray-600">VAT Number: FRB1235476</p>
      </div>
      <div className="flex space-x-2 items-start">
        <Button className="text-red-500 bg-transparent hover:bg-red-50" variant="ghost">
          <TrashIcon className="w-5 h-5" />
          DELETE
        </Button>
        <Button className="text-gray-600 bg-transparent hover:bg-gray-50" variant="ghost">
          <PencilIcon className="w-5 h-5" />
          EDIT
        </Button>
      </div>
    </div>
  )
}

function PencilIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
      <path d="m15 5 4 4" />
    </svg>
  )
}


function TrashIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}
