/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1LYBRdFCfR7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card } from "@/components/ui/card"

export function Rroga() {
  return (
    <Card className="w-[300px] h-[270px] bg-white rounded-lg p-6 shadow flex flex-col items-center">
      <div className="bg-[#FF3B30] p-4 rounded-lg mb-4">
        <WalletIcon className="text-white h-8 w-8" />
      </div>
      <div className="text-center mb-4">
        <p className="text-lg font-semibold">Rrogat</p>
        <p className="text-sm text-gray-500">Mujore</p>
      </div>
      <div className="border-t pt-4 w-full">
        <p className="text-center text-lg font-bold">$2000</p>
      </div>
    </Card>
  )
}

function WalletIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 12V7H5a2 2 0 0 1 0-4h14v4" />
      <path d="M3 5v14a2 2 0 0 0 2 2h16v-5" />
      <path d="M18 12a2 2 0 0 0 0 4h4v-4Z" />
    </svg>
  )
}
