/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6ranbUqUFLO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function Transactions() {
  return (
    <div className="max-w-xl mx-auto p-6 bg-white shadow-lg rounded-lg w-full">
      <div className="flex justify-between items-center mb-4">
        <h1 className="text-2xl font-bold">Your Transactions</h1>
        <button className="bg-gray-200 p-2 rounded-md">
          <CalendarIcon className="h-5 w-5 text-gray-600" />
          01 - 31 March 2024
        </button>
      </div>
      <div>
        <h2 className="font-semibold text-gray-700 mb-2">TE FUNDIT</h2>
        <div className="space-y-4">
          <div className="flex justify-between items-center">
            <div>
              <ArrowDownCircleIcon className="text-red-500" />
              <div>
                <p className="font-semibold">Derivate</p>
                <p className="text-sm text-gray-500">27 March 2024, at 12:30 PM</p>
              </div>
            </div>
            <p className="text-red-500">-$2500</p>
          </div>
          <div className="flex justify-between items-center">
            <div>
              <ArrowUpCircleIcon className="text-green-500" />
              <div>
                <p className="font-semibold">Depozit</p>
                <p className="text-sm text-gray-500">27 March 2024, at 12:30 PM</p>
              </div>
            </div>
            <p className="text-green-500">+$2500</p>
          </div>
        </div>
        <h2 className="font-semibold text-gray-700 my-2">DJE</h2>
        <div className="space-y-4">
          <div className="flex justify-between items-center">
            <div>
              <ArrowUpCircleIcon className="text-green-500" />
              <div>
                <p className="font-semibold">Depozit</p>
                <p className="text-sm text-gray-500">26 March 2024, at 13:45 PM</p>
              </div>
            </div>
            <p className="text-green-500">+$800</p>
          </div>
          <div className="flex justify-between items-center">
            <div>
              <ArrowUpCircleIcon className="text-green-500" />
              <div>
                <p className="font-semibold">Depozit</p>
                <p className="text-sm text-gray-500">26 March 2024, at 12:30 PM</p>
              </div>
            </div>
            <p className="text-green-500">+$1700</p>
          </div>
          <div className="flex justify-between items-center">
            <div>
              <AlertCircleIcon className="text-gray-400" />
              <div>
                <p className="font-semibold">Transfer</p>
                <p className="text-sm text-gray-500">26 March 2024, at 05:00 AM</p>
              </div>
            </div>
            <p className="text-gray-500">Pending</p>
          </div>
        </div>
      </div>
    </div>
  )
}

function AlertCircleIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <line x1="12" x2="12" y1="8" y2="12" />
      <line x1="12" x2="12.01" y1="16" y2="16" />
    </svg>
  )
}


function ArrowDownCircleIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 8v8" />
      <path d="m8 12 4 4 4-4" />
    </svg>
  )
}


function ArrowUpCircleIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m16 12-4-4-4 4" />
      <path d="M12 16V8" />
    </svg>
  )
}


function CalendarIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
    </svg>
  )
}
