/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/kL1oCwFiJ9b
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { fetchUsers } from "@/utils/queries";
import UserModalButton from "../ui/modalButtons/userModalButton";
import { User } from "@/lib/type";
import UserTable from "../tables/user/user-table";

export async function Workers() {
   const punetoret:User[] = await fetchUsers();
   // console.log(punetoret)
   return (
      <div className="bg-white shadow rounded-lg  w-full container pt-4">
         <div className="flex justify-between">
            <h1 className="text-2xl font-bold text-left mb-6">Punëtorët</h1>
            {/* <UserModalButton /> */}
         </div>
         <div className="overflow-hidden rounded-lg">
          <UserTable/>
         </div>
      </div>
   );
}
