import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/providers/toast-provider";
import { SesionProvider } from "@/providers/seesion-provider";
import { ModalProvider } from "@/providers/modal-provider";
// import { KategoriaShepnzimeveModalProvider } from "@/providers/kategoriaShpenzimeve-modal-provider";
// import { KategoriaShepnzimeveModalProvider } from "@/providers/kategoriaShpenzimeve-modal-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Apollo Taxi",
   // description: "Generated by create next app",
   icons: [
      {
         url: "/assets/icons/logo.ico",
         sizes: "16x16",
         type: "image/icon",
      },
   ],
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <head>
            <link rel="icon" href="/logo.ico" />
         </head>
         <body className={(inter.className, ``)}>
            {/* <Dashboard> */}
            <SesionProvider>
               <ToastProvider />
               <ModalProvider />
               {/* <KategoriaShepnzimeveModalProvider/> */}
               {children}
            </SesionProvider>
            {/* </Dashboard> */}
         </body>
      </html>
   );
}
