/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fqFX8XEgvhZ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
   SelectValue,
   SelectTrigger,
   SelectItem,
   SelectContent,
   Select,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Button } from "@/components/ui/button";

import Image from "next/image";
import UserDetail from "../app/assets/images/userphoto.png";
import Credits from "../app/assets/images/Credits to Unsplash.com.png";
import { PersonalInfo } from "./component/personal_Info";
import { Fitimet } from "./component/fitimet";
import { Stats } from "./component/stats";
import { fetchUserByUsername } from "@/utils/queries";
import { Avatar, AvatarFallback, AvatarImage } from "./ui/avatar";
import { getImageUrl } from "@/lib/utils";

export async function UserDetails({ username }: { username: string }) {
   const user = await fetchUserByUsername(username);
  //  console.log(user);
   return (
      <div className="container pt-[28px] pb-[23px]">
         <div className=" p-8 gap-16 pb-[100px]">
            <Image src={UserDetail} alt="Image" className="w-full" />

            <div className=" flex  relative z-30">
               <div className="py-[16.5px] px-[16.5px] pr-5 left-4 border rounded-lg flex gap-[582px] absolute bottom-[-45px] bg-white/90  w-[95%] items-center">
                  <div className="flex items-center ">
                     <Avatar>
                        <AvatarFallback>
                           {user.name.charAt(0)}
                           {user.lastName.charAt(0)}
                        </AvatarFallback>
                     </Avatar>
                     <div className="pl-[22px]">
                        <h1 className="text-xl font-semibold text-black">
                           {user.name + " " + user.lastName}
                        </h1>
                        <span className="text-xl font-semibold text-[#A0AEC0]">
                           {user.email}
                        </span>
                     </div>
                  </div>
                  {/* <div className="">
                     <Button className="bg-white text-red-500">Delete</Button>
                  </div> */}
               </div>
            </div>
         </div>

         <div className="w-full flex items-center justify-center">
            {/* <div className="bg-white w-1/2 rounded-md py-[28px] pl-[21px] text-[#A0AEC0] ">
               <div className="items-center pb-[48px]">
                  <h3 className="text-xl font-semibold text-[#A0AEC0]">
                     TË DREJTAT
                  </h3>
                  <div className=" flex flex-col pt-6 space-y-4 ">
                     <div className="flex items-center gap-2">
                        <Switch id="email-payroll" />
                        <Label htmlFor="email-payroll">Qasje ne financa</Label>
                     </div>
                     <div className="flex items-center gap-2">
                        <Switch id="notify-role-change" />
                        <Label htmlFor="notify-role-change">
                           Qasje tek Puntoret
                        </Label>
                     </div>
                     <div className="flex items-center gap-2">
                        <Switch id="notify-schedule-change" defaultChecked />
                        <Label htmlFor="notify-schedule-change">
                           Shtim i User
                        </Label>
                     </div>
                     <div className="flex items-center gap-2">
                        <Switch id="email-payroll" />
                        <Label htmlFor="email-payroll">
                           Gjenerim i Raporteve
                        </Label>
                     </div>
                  </div>
               </div>
               <div className="items-center pb-[48px]">
                  <h3 className="text-xl font-semibold text-[#A0AEC0]">
                     NJOFTIMET
                  </h3>
                  <div className=" flex flex-col pt-6 space-y-4 ">
                     <div className="flex items-center gap-2">
                        <Switch id="email-payroll" />
                        <Label htmlFor="email-payroll">
                           Dergo Email për paga
                        </Label>
                     </div>
                     <div className="flex items-center gap-2">
                        <Switch id="notify-role-change" />
                        <Label htmlFor="notify-role-change">
                           Njoftim për ndërrimin të rolit
                        </Label>
                     </div>
                     <div className="flex items-center gap-2">
                        <Switch id="notify-schedule-change" defaultChecked />
                        <Label htmlFor="notify-schedule-change">
                           Njoftim për ndërrimin të orarit
                        </Label>
                     </div>
                  </div>
               </div>
               <div className="pb-[48px]">
                  <h3 className="text-xl font-semibold">Role</h3>
                  <div className=" flex flex-col space-y-4 pt-6">
                     <div className="flex items-center gap-2">
                        <Switch id="role-admin" />
                        <Label className="" htmlFor="role-admin">
                           Admin
                        </Label>
                     </div>
                     <div className="flex items-center gap-2">
                        <Switch id="role-primary" defaultChecked />
                        <Label className="" htmlFor="role-primary">
                           Primar
                        </Label>
                     </div>
                     <div className="flex items-center gap-2">
                        <Switch id="role-secondary" />
                        <Label htmlFor="role-secondary">Sekondar</Label>
                     </div>
                     <div className="flex items-center gap-2">
                        <Switch id="role-undeclared" />
                        <Label htmlFor="role-undeclared">Pa Deklaruar</Label>
                     </div>
                  </div>
               </div>
               <div className="pb-[48px]">
                  <h3 className="text-xl font-semibold">Orari</h3>
                  <div className="flex flex-col space-y-4 pt-6">
                     <div className="flex items-center gap-2">
                        <Switch id="shift-morning" />
                        <Label className="" htmlFor="shift-morning">
                           Paradite
                        </Label>
                     </div>
                     <div className="flex items-center gap-2">
                        <Switch id="shift-evening" />
                        <Label htmlFor="shift-evening">Pasdite</Label>
                     </div>
                  </div>
               </div>
            </div> */}
            <div className="flex flex-col w-full justify-between">
               <div className="bg-white rounded-md w-1/2">
                  <PersonalInfo user={user} />
               </div>

               <div className="bg-white">
                  {/* <Stats /> */}
               </div>
            </div>
         </div>
      </div>
   );
}
